# Generated by Django 5.1.5 on 2025-05-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverfirstname', models.CharField(max_length=100)),
                ('driverlastname', models.CharField(max_length=100)),
                ('drivermobileno', models.CharField(max_length=10, unique=True)),
                ('driverpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
