# Generated by Django 5.1.5 on 2025-05-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_holidaytourtariff_hourlyrentaltariff_and_more'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.node'),
            preserve_default=False,
        ),
    ]
