# Generated by Django 5.1.5 on 2025-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driverregistration_city_driverregistration_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='city',
        ),
    ]
