# Generated by Django 5.1.5 on 2025-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driverregistration_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
