# Generated by Django 5.1.5 on 2025-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driverregistration_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='aadhar_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_aadhars/'),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driver_aadhar_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driveraccount_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driveraddress',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driverbank_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driverbranch_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='drivercity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driverifsc_code',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driverlicense_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driverpincode',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driverstate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='license_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
    ]
