# Generated by Django 5.1.5 on 2025-05-04 14:04

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driverregistration_aadhar_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverregistration',
            name='aadhar_picture',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_aadhar_picture),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='license_picture',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_license_picture),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_profile_picture),
        ),
    ]
