# Generated by Django 5.1.5 on 2025-05-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_alter_driverregistration_aadhar_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
