# Generated by Django 5.1.5 on 2025-05-05 06:34

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_driverregistration_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='fitness_certificate',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_fitness),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='fitness_certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='fitness_certificate_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='puc_certificate',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_puc),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='vehicle_insurance',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_insurance),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='vehicle_tax_receipt',
            field=models.ImageField(blank=True, null=True, upload_to=driver.models.upload_tax_receipt),
        ),
    ]
