# Generated by Django 5.1.5 on 2025-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_driverregistration_fitness_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='vehicletype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
