# Generated by Django 5.1.5 on 2025-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driverregistration_vehicletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='vehicletype',
        ),
    ]
