# Generated by Django 5.1.5 on 2025-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_remove_driverregistration_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='vehicletype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
