# Generated by Django 5.2 on 2025-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_driverregistration_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
