# Generated by Django 5.1.5 on 2025-06-18 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_driverregistration_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='driver.driverregistration')),
            ],
        ),
    ]
