# Generated by Django 5.1.5 on 2025-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_alter_driverregistration_driver_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverregistration',
            name='driver_aadhar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='driveraccount_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='driverifsc_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='driverlicense_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
