# Generated by Django 5.2 on 2025-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeID', models.AutoField(primary_key=True, serialize=False)),
                ('nodeInitials', models.CharField(max_length=50)),
                ('nodeAddress', models.CharField(max_length=100)),
                ('nodeCity', models.CharField(max_length=50)),
                ('nodeState', models.CharField(max_length=50)),
                ('nodePincode', models.CharField(max_length=50)),
                ('coordinatorName', models.CharField(max_length=50)),
                ('helplineNumber', models.CharField(max_length=50)),
                ('nodeLocation', models.CharField(max_length=100)),
            ],
        ),
    ]
