# Generated by Django 5.2 on 2025-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='nodeLocation',
            new_name='nodeLatitude',
        ),
        migrations.AddField(
            model_name='node',
            name='nodeLongitude',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
