# Generated by Django 5.2 on 2025-05-01 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_rename_nodelocation_node_nodelatitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodeAddress',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='FixedTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixedTerminalCharges', models.FloatField()),
                ('fixedSurCharges', models.FloatField()),
                ('fixedTax', models.FloatField()),
                ('vansatCommission', models.FloatField()),
                ('driverCommission', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.node')),
            ],
        ),
    ]
