# Generated by Django 5.2 on 2025-05-01 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_node_nodeaddress_fixedtariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kmRange', models.CharField(max_length=50)),
                ('hatchback', models.FloatField()),
                ('seden', models.FloatField()),
                ('premiumSeden', models.FloatField()),
                ('muv', models.FloatField()),
                ('suv', models.FloatField()),
                ('premiumSUV', models.FloatField()),
                ('acTravellar', models.FloatField()),
                ('buses', models.FloatField()),
                ('hatchbackWatingCharges', models.FloatField()),
                ('sedenWatingCharges', models.FloatField()),
                ('premiumSedenWatingCharges', models.FloatField()),
                ('muvWatingCharges', models.FloatField()),
                ('suvWatingCharges', models.FloatField()),
                ('premiumSUVWatingCharges', models.FloatField()),
                ('acTravellarWatingCharges', models.FloatField()),
                ('busesWatingCharges', models.FloatField()),
                ('cancellationCharges', models.FloatField()),
                ('misleniousCharges', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.node')),
            ],
        ),
    ]
