# Generated by Django 5.2 on 2025-05-03 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0005_railwaytariff"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayTourTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("packageName", models.CharField(max_length=50)),
                ("hatchback", models.FloatField()),
                ("seden", models.FloatField()),
                ("premiumSeden", models.FloatField()),
                ("muv", models.FloatField()),
                ("suv", models.FloatField()),
                ("premiumSUV", models.FloatField()),
                ("acTravellar", models.FloatField()),
                ("buses", models.FloatField()),
                ("hatchbackWatingCharges", models.FloatField()),
                ("sedenWatingCharges", models.FloatField()),
                ("premiumSedenWatingCharges", models.FloatField()),
                ("muvWatingCharges", models.FloatField()),
                ("suvWatingCharges", models.FloatField()),
                ("premiumSUVWatingCharges", models.FloatField()),
                ("acTravellarWatingCharges", models.FloatField()),
                ("busesWatingCharges", models.FloatField()),
                ("cancellationCharges", models.FloatField()),
                ("misleniousCharges", models.FloatField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyRentalTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hours", models.CharField(max_length=50)),
                ("kms", models.CharField(max_length=50)),
                ("hatchback", models.FloatField()),
                ("seden", models.FloatField()),
                ("premiumSeden", models.FloatField()),
                ("muv", models.FloatField()),
                ("suv", models.FloatField()),
                ("premiumSUV", models.FloatField()),
                ("acTravellar", models.FloatField()),
                ("buses", models.FloatField()),
                ("hatchbackWatingCharges", models.FloatField()),
                ("sedenWatingCharges", models.FloatField()),
                ("premiumSedenWatingCharges", models.FloatField()),
                ("muvWatingCharges", models.FloatField()),
                ("suvWatingCharges", models.FloatField()),
                ("premiumSUVWatingCharges", models.FloatField()),
                ("acTravellarWatingCharges", models.FloatField()),
                ("busesWatingCharges", models.FloatField()),
                ("extraMin", models.FloatField()),
                ("extraKms", models.FloatField()),
                ("cancellationCharges", models.FloatField()),
                ("misleniousCharges", models.FloatField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutstationTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("kmRange", models.CharField(max_length=50)),
                ("hatchback", models.FloatField()),
                ("seden", models.FloatField()),
                ("premiumSeden", models.FloatField()),
                ("muv", models.FloatField()),
                ("suv", models.FloatField()),
                ("premiumSUV", models.FloatField()),
                ("acTravellar", models.FloatField()),
                ("buses", models.FloatField()),
                ("hatchbackWatingCharges", models.FloatField()),
                ("sedenWatingCharges", models.FloatField()),
                ("premiumSedenWatingCharges", models.FloatField()),
                ("muvWatingCharges", models.FloatField()),
                ("suvWatingCharges", models.FloatField()),
                ("premiumSUVWatingCharges", models.FloatField()),
                ("acTravellarWatingCharges", models.FloatField()),
                ("busesWatingCharges", models.FloatField()),
                ("cancellationCharges", models.FloatField()),
                ("misleniousCharges", models.FloatField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.node",
                    ),
                ),
            ],
        ),
    ]
