# Generated by Django 5.2 on 2025-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_holidaytourtariff_hourlyrentaltariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nodeName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
