# Generated by Django 5.1.5 on 2025-05-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_node_nodename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=50)),
                ('employeeEmail', models.EmailField(max_length=254)),
                ('employeeMobile', models.CharField(max_length=10)),
                ('employeeRole', models.CharField(max_length=50)),
                ('employeeAddress', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('empSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empJoiningDate', models.DateField()),
                ('employeeAadhar', models.CharField(max_length=12)),
                ('empNodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.node')),
            ],
        ),
    ]
