# Generated by Django 5.1.5 on 2025-05-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_employee_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_available',
        ),
    ]
