# Generated by Django 5.1.5 on 2025-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_remove_employee_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.CharField(default='Available', max_length=15),
        ),
    ]
