# Generated by Django 5.1.5 on 2025-05-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_employee_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='availability',
        ),
    ]
