# Generated by Django 5.0.6 on 2025-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0013_employee_is_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("booking_id", models.CharField(max_length=100, unique=True)),
                ("passenger_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("email_id", models.EmailField(max_length=254)),
                ("from_city", models.CharField(max_length=100)),
                ("to_city", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("driver_name", models.CharField(max_length=100)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("driver_contact", models.CharField(max_length=15)),
                ("payment_type", models.CharField(max_length=20)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "terminal_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("surcharges", models.DecimalField(decimal_places=2, max_digits=10)),
                ("taxes", models.CharField(max_length=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
