# Generated by Django 5.0.6 on 2025-05-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0014_trip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="email_id",
            new_name="email",
        ),
    ]
