# Generated by Django 5.0.6 on 2025-05-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0015_rename_email_id_trip_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="email",
            new_name="email_id",
        ),
    ]
