# Generated by Django 5.0.6 on 2025-05-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0016_rename_email_trip_email_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="otp",
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
