# Generated by Django 5.1.5 on 2025-05-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_trip_otp_trip_otp_verified'),
        ('driver', '0012_driverregistration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='driver.driverregistration'),
            preserve_default=False,
        ),
    ]
