# Generated by Django 5.1.5 on 2025-05-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_trip_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
    ]
