# Generated by Django 5.1.5 on 2025-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0019_remove_trip_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
