# Generated by Django 5.1.5 on 2025-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0020_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='extra_charges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='extra_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
