# Generated by Django 5.1.5 on 2025-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0021_trip_extra_charges_trip_extra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='vansat_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
