# Generated by Django 5.1.5 on 2025-08-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0022_trip_driver_commission_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='driver_commission_amount',
            new_name='driver_commission',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='vansat_commission_amount',
            new_name='vansat_commission',
        ),
    ]
