# Generated by Django 5.1.5 on 2025-08-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0023_rename_driver_commission_amount_trip_driver_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
