# Generated by Django 5.1.5 on 2025-08-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0024_trip_end_time_trip_start_time_trip_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
