# Generated by Django 5.1.5 on 2025-08-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0025_trip_location_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='location_history',
        ),
    ]
