# Generated by Django 5.1.5 on 2025-08-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0027_triplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripLocation',
        ),
    ]
