# Generated by Django 5.1.5 on 2025-08-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0029_triplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='triplocation',
            name='locations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='triplocation',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='admin_dashboard.trip'),
        ),
    ]
