# Generated by Django 5.1.5 on 2025-08-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0030_remove_triplocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='locations',
            field=models.JSONField(default=list),
        ),
    ]
