# Generated by Django 5.1.5 on 2025-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0031_alter_triplocation_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='locations',
            field=models.JSONField(default=dict),
        ),
    ]
