# Generated by Django 5.1.5 on 2025-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0032_alter_triplocation_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='gst_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
