# Generated by Django 5.1.5 on 2025-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0033_trip_company_name_trip_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='company_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
